services:
    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        restart: always
        command: tunnel run --token ${TUNNEL_TOKEN}
        networks:
            - chat
    next-app:
        image: ghcr.io/marcusaurelys/bos-next:latest
        container_name: next-app
        restart: always
        ports: 
            - 3000:3000
        networks:
            - chat
        env_file: '.env'
    flask-app:
        image: ghcr.io/marcusaurelys/bos-flask:latest
        container_name: flask-app
        restart: always
        ports:
            - 5000:5000
        depends_on:
            - chromadb
        networks:
            - chat
        env_file: './server/.env'
    chromadb:
        image: chromadb/chroma:latest
        container_name: chromadb
        volumes:
            - ./chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - PERSIST_DIRECTORY=/chroma/chroma
        ports:
            - 8000:8000
        networks:
            - chat

networks:
    chat:
        driver: bridge
