services:
    next-app:
        image: ghcr.io/marcusaurelys/bos-next:latest
        pull_policy: always
        container_name: next-app
        restart: always
        depends_on:
            - mongo
        ports: 
            - 3000:3000
        network_mode: 'host'
        env_file: '.env'
    flask-app:
        image: ghcr.io/marcusaurelys/bos-flask:latest
        pull_policy: always
        container_name: flask-app
        restart: always
        ports:
            - 5000:5000
        depends_on:
            - chromadb
        networks:
            - chat
        env_file: './server/.env'
    chromadb:
        image: chromadb/chroma:0.5.4
        container_name: chromadb
        restart: always
        volumes:
            - ./chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - PERSIST_DIRECTORY=/chroma/chroma
        ports:
            - 8000:8000
        networks:
            - chat
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - ./mongodb:/data/db
        ports: 
            - 27017:27017
        networks: 
            - chat
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        networks:
            - chat  

networks:
    chat:
        driver: bridge
