import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import NavBar from "../components/NavBar";
import { validateUser } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await validateUser(['admin', 'member'])
  

  return ( <>

  <NavBar user={user}/>
    <div>
        {children}
    </div>

  </>
    
  );
}
