import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import NavBar from "../components/NavBar";
import { cookies } from "next/headers";
import { getToken } from "@/db/users";
import DataContextProvider from '@/contexts/DataContext'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = cookies()
  const token = cookieStore.get("session")
  const user = await getToken(token?.value)

  async function handleLogout () {
    "use server"
    cookies().delete("session")

  }
  
  return ( 
  <>
  <NavBar user={user} handleLogout={handleLogout}/>
    <DataContextProvider>
      {children}
    </DataContextProvider>
  </>
  );
  
}
