import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "../components/NavBar";
import DataContextProvider from '@/contexts/DataContext'
import { cookies } from 'next/headers'
import { get_user_by_token } from '@/db/users'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "businessOS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return ( 
  <>
    <NavBar/>
      {children}
  </>
  );
  
}
