name: Let's do it in one file because workflow_run fucking sucks

on: 
  push:
    branches: [ "master" ]

jobs:
  ci_cd:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to Github Container Registry
        run: |
          docker login --username marcusaurelys --password ${{ secrets.docker_token }} ghcr.io

      - name: Build the Next.js app
        run: |
          docker build --build-arg MONGO_URI=${{secrets.MONGO_URI}} --build-arg MONGO_URI_PRODUCTION="mongodb://mongo:27017" --build-arg HOST=${{secrets.HOST}}:3000 --build-arg CRISP_WEBSITE_ID=${{secrets.CRISP_WEBSITE_ID}} --build-arg CRISP_API_ID=${{secrets.CRISP_API_ID}} --build-arg CRISP_API_KEY=${{secrets.CRISP_API_KEY}} --build-arg CHATBOT_URL=${{secrets.CHATBOT_URL}} --build-arg CHATBOT_API_KEY=${{ secrets.CHATBOT_API_KEY}} . --tag ghcr.io/marcusaurelys/bos-next:latest
          docker push ghcr.io/marcusaurelys/bos-next:latest  
      
      - name: Build the Flask app
        run: |
          docker build ./server --tag ghcr.io/marcusaurelys/bos-flask:latest
          docker push ghcr.io/marcusaurelys/bos-flask:latest
      
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts

      - name: Copy Docker Compose YAML to Production Instance
        run: |
          scp -i ~/.ssh/id_ed25519 docker-compose-prod.yaml ${{ secrets.USER_AND_HOST }}:~
           
      - name: Login using SSH then Spin down old instance and remove unused containers then Spin up containers defined in YAML
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.USER_AND_HOST }} 'docker login --username marcusaurelys --password ${{ secrets.docker_token }} ghcr.io && docker compose -f docker-compose-prod.yaml down --remove-orphans && docker compose -f docker-compose-prod.yaml up -d && docker system prune -f'
